### ISSUE TITLE
Update Goonj rules to work in DEA

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/Goonj#103]
### As is:
Currently in Activity and Distribution registration, we show 'Other Block' form element(input the name of the block) when 'Other' block is selected in address.

### Issue:
The condition for the above is achieved by below form element rule

```
'use strict';
({params, imports}) => {
  const individual = params.entity;
  const moment = imports.moment;
  const formElement = params.formElement;
  const _ = imports.lodash;
  let visibility = false;
  const condition11 = new imports.rulesConfig.RuleCondition({individual, formElement}).when.lowestAddressLevel.defined.matches();
  const isDefined = individual.lowestAddressLevel !== undefined && individual.lowestAddressLevel.locationMappings.length !== 0;
  //&& individual.lowestAddressLevel.isSelected;
  if (isDefined) {
    const block = individual.lowestAddressLevel.locationMappings[0].that.parent.name;
    if (block === 'Other') {
      visibility = true;
    }
    else {
      visibility = false;
    }
  }
  return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility);
};
```
 But `locationMappings` is not available in DEA. 

### Analysis:
locationMappings as such is not much useful. In product we are planning to remove the location_location_mapping table. Hence we are not adding support for rules that access locationMappings.

### AC:
- Rule has to be changed to make use of individual.lowestAddressLevel.titleLineage incase locationMappings is not present(which is the case in webapp), to figure out "Other Block" visibility.

Example individual.lowestAddressLevel.titleLineage value:

"Karnataka, Bengaluru, Indiranagara, Binnamangala"
- Should be changed in both Activity and Distribution registration
- Cover any cases missed about w.r to the above issue.
- If there is any other better alternative solution feel free to do that.
- Misc: Select the 'Search' option for `Activities Done` and `Inventory Id` subject concept form elements to make it work in DEA.
- All the above can be tested in prerelease env DEA to make sure it is working.

**Comment by himeshr** [comment]
Done
