### ISSUE TITLE
Activity Registration form : Text changes

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#106]
### Requirement

Changes in text
1. In the space ‘Type of School’, it
can be replaced with ‘Type of
Educational Institute’
2. ~In selection options,
‘tution/training/vocational centre’
cane be replaced with
‘Tuition/Learning Centre’~
3. “Was Disclaimer Form Filled?” needs to be replaced
with “Was Undertaking Form Filled?”

### Details

"Activity Registration Form:

Under Form Element Group : Activity Details

1. Question ""Type of school"" change the text to ""Type of Educational Institute""

2. ~Change option ‘tution/training/vocational centre’ to "Tuition/Learning Centre"~

3. Question ""“Was Disclaimer Form Filled?” change it to “Was Undertaking Form Filled?”"

**Comment by vedfordev** [comment]
@himeshr for 2nd Do I need to create new option or change the same option ??

**Comment by vedfordev** [comment]
1st and 3rd is done

**Comment by himeshr** [comment]
> [@himeshr](https://github.com/himeshr) for 2nd Do I need to create new option or change the same option ??

Its a rename only

**Comment by Dinesh2019** [comment]
QA Refrence video : 

[Click here to watch video](https://drive.google.com/file/d/1WHJMKUqwU56j5igsubVuJsAJYVEiWGeh/view?usp=drive_link)

**Comment by vedfordev** [comment]
@himeshr find below
1. Type of Educational Institute:- Only fe name change
2. Tuition/Learning Centre:- not present in mapping metadata
3. Was Undertaking Form Filled?:- Only fe name change
