### ISSUE TITLE
Activity Registration Form : Form element additions

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#107]
### Requirement

```
"When ""Other"" is selected then text box should appear for entering the ""Other Details""

1. For ""Any Other"" in Activity form for activities done in school, when S2S is selected in Activity form.
2. For ""Any Other"" in Activity form form for Objective of work"
```

### Details

```
"Activity Registration Form:

Under Form Element Group : Activity Details

1. Question ""Work Objective"" if answer selected is ""Any other not given above"" add another question ""Any other not given above, please specify""

2. Question ""Type of initiative"" if answer selected is ""S2S "", add another question ""Other Initiative, please specify"""
```

**Comment by vedfordev** [comment]
@himeshr Please find below
1. I checked current form. There is field **Specify Other** after **Work Objective**. But it has logic for field **Objective of work**. Do I need to change this or need to create new one??
2. For Second question after which question I have to add ??

**Comment by himeshr** [comment]
> @himeshr Please find below
> 
> 1. I checked current form. There is field **Specify Other** after **Work Objective**. But it has logic for field **Objective of work**. Do I need to change this or need to create new one??
> 2. For Second question after which question I have to add ??

Ignore the details here.. In general, this card is for Changes to Activity form.
Refer to the Avni Goonj Tech Specifications to determine the exact changes needed in Activity Form.

**Comment by vedfordev** [comment]
@himeshr Ok, I've asked them for clarification on sheet.

**Comment by Dinesh2019** [comment]
@himeshr @vedfordev in the requirment sheet for s2s it is mentioned as specify other but in AC it is mentioned as Other Initiative, please specify the development is done as specify other can you confirm which one we have to use.


QA References video : 

[Click here to watch video](https://drive.google.com/file/d/1wyLegEjqQ0U45bLsJHlT5uOIR53Gjfws/view?usp=drive_link)

**Comment by vedfordev** [comment]
@himeshr find below

1. Any other not given above, please specify:- Only rule change
2. Specify other activity:- newly created

code : otherActivity created and checked in payload.

**Comment by Athulya-benny** [comment]
@himeshr this is working fine
