### ISSUE TITLE
Distribution Registration Form Addition and Modification Changes

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#108]
### Requirement

```
"In distribution form in Specific Initiative details:-
1. Replace None by ""Any  Other""
2. When 'Any Other' is selected show text box ""Other Details"" should be shown"
```

### Details

```
"Distribution Registration Form
Under Form Element Group ""Specific Initiative details

1. Question ""Material Given for"" deprecate option ""None"", introduce new option ""Any  Other""

2. When ""Any Other"" is selected add another question ""Any other material given, please specify"""
```

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1vZYI2LqpOJpjs4aMR3wZT-zGtmuW8INz/view?usp=drive_link)

**Comment by vedfordev** [comment]
@himeshr 
1. Material Given for:- not present in mapping metadata
2. Any other material given:- newly created 

added otherMaterialGiven checked in payload

**Comment by Athulya-benny** [comment]
@himeshr its working fine. But When we select 'any other' for 'material given for' field, the dependent field appearing in Avni is "Any other material given, please specify" but in salesforce, it is 'other details'.Will it cause any issues?
