### ISSUE TITLE
Distribution Registration Form : Remove Question

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#109]
### Requirement

```
"In Distribution

Total No. of Receivers should be removed"
```

### Details

```
"Distribution Registration Form,
Under Form Element Group : Inventory details

Remove question, ""Total Number of Receivers"""
```

**Comment by vedfordev** [comment]
@himeshr Do I need to remove from the code as well ??

**Comment by himeshr** [comment]
> @himeshr Do I need to remove from the code as well ??

No, its required to sync data from older entities.. it becomes optional on Salesforce API

Mention the same in the excel sheet
