### ISSUE TITLE
Restrict number of media content that can be uploaded for Media fields across various forms

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#110]
### Requirement

```
Restrict number of photographs that can be uploaded per field.
```

### Details
The media image count restrictions are specified in the "Read Me" sheet..
https://docs.google.com/spreadsheets/d/19hf-T7mSn922qZcZQQMtZW2VQaaseQNZ-B2mzcMbDLk/edit?gid=1368060023#gid=1368060023

```
Enforce via rule. Need more info from Goonj for the various Media fields on the count for each of them.
```

**Comment by Athulya-benny** [comment]
@himeshr 
Can we set the limit for the Vaapsi initiative too in distribution form with
Distribution 2, receivers list no limit, Undertaking form not applicable

**Comment by himeshr** [comment]
Sure, marked the same in Avni Tech Specifications sheet


> @himeshr Can we set the limit for the Vaapsi initiative too in distribution form with Distribution 2, receivers list no limit, Undertaking form not applicable

**Comment by vedfordev** [comment]
> Sure, marked the same in Avni Tech Specifications sheet
> 
> > [@himeshr](https://github.com/himeshr) Can we set the limit for the Vaapsi initiative too in distribution form with Distribution 2, receivers list no limit, Undertaking form not applicable

done with changes

**Comment by vedfordev** [comment]
this changes done
> @himeshr Can we set the limit for the Vaapsi initiative too in distribution form with Distribution 2, receivers list no limit, Undertaking form not applicable
