### ISSUE TITLE
Additional Search Filters

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#111]
### Requirement

```
"In Avni Search Bar

Village Name as a Search bar option in Search  //  Universal Search Bar options in Search Bar "
```

### Details

```
In Search Filters, there will be an address level filter
```

**Comment by vedfordev** [comment]
Created Address Search Filter for every subject type.

**Comment by Dinesh2019** [comment]
Unable to select the address in the cilent app 

Refer video : 

[Click here to watch video](https://drive.google.com/file/d/1tFmSOIOWWnaGfRC1gxSc43s1PbJcL7dN/view?usp=drive_link)

**Comment by vedfordev** [comment]
For performance created bug card [Card](https://github.com/avniproject/avni-client/issues/1515)

**Comment by vedfordev** [comment]
@dinesh2019 for performance raise bug card. please check with catchment which have lower level locations.

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1lp2dGaVYManztqFVklXhTa-xsi0a9SPw/view?usp=drive_link)

**Comment by himeshr** [comment]
This can only be considered done after 10.1.0 release..

**Comment by himeshr** [comment]
This is now working in Prod environment after 10.0.4 release
