### ISSUE TITLE
Setup dev organisation from the production organisation

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#112]
Setup dev organisation from the production organisation
- Compare Avni server bundle for Goonj prod and uat orgs and ensure no discrepancy
- Compare Avni Integration bundle for Goonj prod and uat orgs and ensure no discrepancy
- Setup local dev env using Avni staging integration bundle

---

[Backup Before Work](https://drive.google.com/drive/folders/128JU1KipEl1itlD6TBtJ_TlhvGuhopq7)

**Comment by vedfordev** [comment]
There are metadata difference in uat and prod. So, I am unable to proceed. local setup is done.
https://drive.google.com/drive/folders/128JU1KipEl1itlD6TBtJ_TlhvGuhopq7

Task need to done after she confirm:

- [x] 1. Backup User-sync-settings to store the synConceptValues 

- [x] 2. In Uat env, Cleanup transaction-data and metadata

- [x] 3. In Uat env, Upload prod bundle

- [x] 4. Restore  User-sync-settings

- [x] 5. Clear error-records and error-record logs in staging-int related to goonj 

- [x] 6. Upload prod-int bundle to stag-int

- [x] 7. Set the entitySyncStatus markers for all goonj entities to be 6 months ago and get transactional data into uat org

**Comment by vedfordev** [comment]
@himeshr 6th step not done as there are no major changes
