### ISSUE TITLE
Change in synch date for WB - Dispatches (4239)

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#113]
- Change in synch date for WB - Dispatches (4239)
- "Freshdesk Ticket Link 4239 - Filter based on registration date on Dashboard"
- https://avni.freshdesk.com/a/tickets/4239

**Comment by vedfordev** [comment]
@himeshr applied in all report cards comes under **Overall statistics** Dashboard.  I applied logic Entity.registrationDate >= selected registrationDate.

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1SKMs53jS6a0i6ykBO1U0HE9RXams3lVX/view?usp=drive_link)
