### ISSUE TITLE
Additional check on No of working days (4070)

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#114]
- Additional check on No of working days (4070)
[Freshdesk Ticket Link 4070](https://avni.freshdesk.com/a/tickets/4070)

**Comment by vedfordev** [comment]
@himeshr Asked them for error message. Once they clarify. I will proceed.

**Comment by Dinesh2019** [comment]
@vedfordev if we gave the values as decimal then the system is accepting can you confirm if decimal is allowed 

QA Reference video : 

[Click here to watch](https://drive.google.com/file/d/1LWl1SuKwj2awUZKpxtg8vbknRkratHU0/view?usp=drive_link)

**Comment by vedfordev** [comment]
@dinesh2019 I've added negative check. the decimal value already accepted

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1kWBsiM17-sHojTgQp_F6H9y4DJSmg5sB/view?usp=drive_link)

**Comment by Athulya-benny** [comment]
@himeshr this is working fine in Avni
