### ISSUE TITLE
Goonj Distribution and activity forms bugs consolidated card

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#116]
## Issues
- In both Activity and Distribution forms, if we select "Other" village
    - on client "Other Village*" field is not showing 
    - on DEA, "Other Village*" field is shown as expected 
    
- In Activity form, Add Negative value validation error message for Activity form fields mentioned below, when value is less than or equal to zero
```
No of working days : "Number of Working Days should be more than 0. Please enter a valid value."
Number of days of participation: "Number of Days of Participation should be more than 0. Please enter a valid value."
Number of Participants (Male): "Number of  Male participants cannot be less than 0. Please enter a valid value."
Number of Participants (Female): "Number of Female participants cannot be less than 0. Please enter a valid value."
Number of Participants (Other): "Number of  Other participants cannot be less than 0. Please enter a valid value."
```    

- In Distribution form, rename not done for "Type of school" text to "Type of Educational Institute"

**Comment by vedfordev** [comment]
> * In both Activity and Distribution forms, if we select "Other" village
>   
>   * on client "Other Village*" field is not showing
>   * on DEA, "Other Village*" field is shown as expected

@himeshr it is working but when we are selecting next option. checked in rule it is not executed when we are selecting block or village. It seems bug. checked in 9.4, 10.0 and 10.0.1


https://github.com/user-attachments/assets/49220e2b-11ce-4e4c-ae46-e5cf189c4716

**Comment by vedfordev** [comment]
> * In Activity form, Add Negative value validation error message for Activity form fields mentioned below, when value is less than or equal to zero
> 
> ```
> No of working days : "Number of Working Days should be more than 0. Please enter a valid value."
> Number of days of participation: "Number of Days of Participation should be more than 0. Please enter a valid value."
> ```

@himeshr rule was already there and worked for me. find validation for negative was missing. added validation for negative value.

**Comment by himeshr** [comment]
Found 2 issues during integration testing:
- In activity, Changing option ‘tution/training/vocational centre’ to "Tuition/Learning Centre" is breaking on salesforce
- In Distribution, Salesforce has not yet provided support for new api field "otherMaterialGiven" 
```
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "[{"message":"Unknown field: DistributionService.DistributionWrapper.otherMaterialGiven at [line:1, column:2298]","errorCode":"JSON_PARSER_ERROR"}]"
```

**Comment by himeshr** [comment]
[GoonjIntegrationErrorsOct04.txt](https://github.com/user-attachments/files/17257206/GoonjIntegrationErrorsOct04.txt)

**Comment by himeshr** [comment]
~Minor bug in activity:~

<img width="635" alt="Screenshot 2024-10-04 at 5 15 13 PM" src="https://github.com/user-attachments/assets/64d9b98c-717e-402e-8e4e-0d9376a5c034">

**Comment by himeshr** [comment]
> Minor bug in activity:
**Seems to be a requirement for NJPC type activity, not an issue**

**Comment by vedfordev** [comment]
### API Field Changes (Given by Client)


Activity

OtherActivity -> OtherDetails
WasDisclaimerFormFilled -> WasUndertakingFormFilled


Distribution

DisclaimerPhotographs -> UndertakingFormPhotographs
OtherMaterialGiven -> OtherDetails 

@himeshr Open this card for new changes for phase-1.

**Comment by himeshr** [comment]
All Integration issues are resolved and was able to sync Different types of Activity and Distribution from Avni UAT to Salesforce Partial Env.

**Comment by himeshr** [comment]
## SQL changes to update lastModifiedDateTime for reportCards and dashboardFilters to before endOfLife1 cutOffDate..

```sql

reset role;

set role gvamp_uat;

-- No fix needed for below entities

select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_section order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_section_card_mapping order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard order by last_modified_date_time desc;

-- Fix needed for report_card
select organisation_id, last_modified_date_time, age(last_modified_date_time, created_date_time) from report_card order by last_modified_date_time desc;
-- 356 2024-10-14 11:50:08.083 +00:00 for report_card

-- '2024-10-14 11:33:10.628 +00:00'

update report_card
set last_modified_date_time = '2024-09-26 15:21:31.657 +00:00'::timestamptz+ (random() * 1000 * (interval '1 millisecond'))
where organisation_id = 356 and last_modified_date_time >= '2024-10-14 11:33:10.628 +00:00'::timestamptz;

-- Fix needed for dashboard_filter
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_filter order by last_modified_date_time desc;
-- 356 '2024-10-14 11:12:10.628 +00:00' for dashboard_filter

update dashboard_filter
set last_modified_date_time = '2024-09-26 15:21:31.657 +00:00'::timestamptz+ (random() * 1000 * (interval '1 millisecond'))
where organisation_id = 356 and last_modified_date_time >= '2024-10-14 11:12:10.628 +00:00'::timestamptz;



```
