### ISSUE TITLE
Provide Status API to check status of Goonj Adhoc API task

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#120]
## AC

Provide Status API to check status of Goonj Adhoc API task, based on cron job status
- Waiting, Completed, Error, in-progress, etc

In Avni-Goonj Handbook documentation:
 - some small paragraphs about how to invoke the trigger and monitor the status
 - Attaching a postman collection with the sample requests

**Comment by vedfordev** [comment]
@himeshr added documentation at last in handbook moving card to review
