### ISSUE TITLE
Handle invocation of Goonj Adhoc API

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#121]
## AC
On invocation of Goonj Adhoc API task, 
- create a CronTrigger as per input frequency and
- return the CronJob details in response

## SQL
```sql
CREATE TABLE goonj_adhoc_task
(
    id                   SERIAL PRIMARY KEY,
    uuid                 CHARACTER VARYING(255) NOT NULL,
    integration_system_id int not null references integration_system (id),
    is_voided            BOOLEAN,
    integration_task   CHARACTER VARYING(255) NOT NULL,
    task_config          JSONB,
    cron                 CHARACTER VARYING(255) NOT NULL,
    cut_off_date_time    TIMESTAMP              NOT NULL,
    status               CHARACTER VARYING(255) NOT NULL,
    created_date_time      TIMESTAMP              NOT NULL,
    last_modified_date_time TIMESTAMP              NOT NULL
);

```

**Comment by himeshr** [comment]
## QA issues found
- triggerDateTime and cutOffDateTime should take input in IST and convert it internally to UTC
- Timestamp expected should be "2024-10-16 10:10:10" and not "2024:10:16 10:10:10"
- When we invoke request for Salesforce sid fetch(Demand, Inventory, Dispatch) with normal spaces, it fails, due to url encoding issue, we are forced to send something like below instead
    Errored content:
    "taskConfig": {
        "account": "Goonj Dhrangadhra"
    },
    Working content:
    "taskConfig": {
        "account": "Goonj%20Dhrangadhra"
    },
- Adhoc triggers do not honour "cutOffDateTime", uses task specific internal read_upto_date_time value instead
{
    "task" : "AvniActivity",
    "taskConfig" : {"account":"Goonj%20Kerala", "state": "Kerala"},
    "triggerDateTime" : "2024:11:14 12:30:00",
    "cutOffDateTime" : "2024:06:15 10:10:10"
}
- During invocation of Avni External Subject GET API, with Concept filter, receiving error that concept name doesnot exist, even though it does. (Avni server bug https://github.com/avniproject/avni-server/issues/821)

**Comment by vedfordev** [comment]
@himeshr 

Other task completed. timestamp task in response is pending. it takes ist in process. moving card to review.

**Comment by himeshr** [comment]
Found following issues during code-review:
- State filter is also not encoded before generating request url for Salesforce calls
- IntegrationTask enum should be used in DTO to avoid invalid values for task field
- Use IntegrationTask helper methods isSalesforceSourceTask(), isInvalidTask() and isAvniSourceTask()
- Fix dateTime format issue with adhocTaskResponse for triggerDateTime and cutoffdatetime
- Add validations for state and account taskConfig fields
