### ISSUE TITLE
Fix rules to display OtherBlock and OtherVillage fields in Avni Source Entity forms

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#123]
## AC

Fix rules to display OtherBlock and OtherVillage fields in Avni Source Entity forms, i.e. for Activity, Distribution and Dispatch Receipt forms

- In Goonj prod org, Correct this issue for Activity, Distribution and Dispatch Receipt forms "OtherBlock" and "OtherVillage" field rules. Replace occurrences of 
```individual.lowestAddressLevel.locationMappings.length !== 0```
 with
 ```!_.isEmpty(individual.lowestAddressLevel.locationMappings)```
 
 - In Goonj UAT org, gvamp_uat ,  Copy the rules from goonj prod for Activity, Distribution and Dispatch Receipt forms "OtherBlock" and "OtherVillage" field rules

**Comment by himeshr** [comment]
This issue is a regression of fix made as part of https://github.com/avniproject/avni-webapp/issues/1252
In general, Implementation freshDev and support team should ensure that they use latest copy of prod bundle to make incremental changes in UAT org and after testing upload the same to Prod.
Never make changes directly in prod org.

**Comment by vedfordev** [comment]
> * !_.isEmpty(individual.lowestAddressLevel.locationMappings)

Only Activity and Distribution have other block and other village

![Image](https://github.com/user-attachments/assets/e454d79b-0976-497b-be19-ec8d7a39a251)

**Comment by vedfordev** [comment]
minor issue avniproject/avni-client/issues/1533

**Comment by himeshr** [comment]
Verified that this is working fine on client and DEA
