### ISSUE TITLE
Display request body corresponding to each of the External errors in Metabase error report

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#126]
## Need
Currenly only error is displayed and need to raise tickets for getting the request bodies for checks. So for external 3 if we can have request bodies as part of the metabase information then it will reduce tickets and time taken for resolution.

## AC

- Display request body corresponding to each of the External errors. 
- Also include state, district, etc information in error table 
- Limit ErrorMessage content stored in db table column to be max of 1000 chars
[Report Link](https://reporting.avniproject.org/question/2918-goonj-production-error-details)

**Comment by vedfordev** [comment]
alter table public.error_record_log
    add error_body jsonb not null;

-- column reordering is not supported public.error_record_log.error_body

**Comment by vedfordev** [comment]
@himeshr error body part is done. tested it with adhoc task. 

```
{"Activities": [{"Block": "Ambalappuzha", "State": "Kerala", "Length": 0.0, "Breadth": 0.0, "Diameter": 0.0, "District": "Alappuzha", "SourceId": "5f8cbda4-b1a2-4133-8dbe-8692ff21d1cd", "CreatedBy": "shivangi@gvamp_uat", "ModifiedBy": "salesforce@gvamp_uat", "DepthHeight": 0.0, "ActivityType": "Miscellaneous", "OtherSubType": "Some other activity", "nameOfAccount": "Goonj Kerala", "OtherObjective": "Some other objective", "ActivityEndDate": "2024-10-18", "ActivitySubType": "Others", "NoofWorkingDays": 1, "FormCrossChecked": "No", "TypeofInitiative": "CFW", "ActivityStartDate": "2024-10-18", "ObjectiveofCFWwork": "Any other not given above", "LocalityVillageName": "Ambalappuzha", "NoofparticipantsMaleCFW": 5, "NoofparticipantsCFWOther": 0, "NoofparticipantsMaleNJPC": 0, "WasUndertakingFormFilled": "No", "NoofparticipantsFemaleCFW": 8, "NoofparticipantsNJPCOther": 0, "NoofparticipantsFemaleNJPC": 0, "SchoolAanganwadiLearningCenterName": "None"}]}



{"State": "Rajasthan", "DemandId": "a1CC3000002NfXZMA0", "District": "Almora", "AccountId": "001C300000IB6R7IAL", "DemandName": "2024/ACC-243980/RAJ/354", "AccountName": "Goonj Avni", "DemandStatus": "Approved", "DispatchStatus": "Unattended", "NumberOfPeople": 12.0, "TypeOfDisaster": "Cyclone", "TargetCommunity": "Adolescents", "LastUpdatedDateTime": "2024-11-07T11:59:58.000Z"}

```

there is no naming convention for address in every dto. So I am unable to set address
