### ISSUE TITLE
[Goonj] UAT feedback Action items

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#14]
- [x] Make "Target Community" field Multi-select in Demand Registration form.
- [x] If Kit is selected in Type of Material, then Unit should not be shown. This will be applicable for Dispatch, Dispatch Receipt and Distribution encounter.
- [x] In Activity encounter, under Measurement type details - for Length, Breadth, Height, Depth all fields add unit as Feet.
- [x] Error message for Distribution date is not correct.
- [x] "Numbers" not showing for required combinations in measurement.
- [x] Distribution form - Materials distributed group form element - The field "Quantity" should not allow a value that is more than the Quantity mentioned in Dispatch receipt form for the specific type of material (i.e. Kit/Contributed Item/Purchased item)
- [x] Type of Initiative to only have three options in Activity encounter: "DFW", "S2S" and "NJPC". 
- [x] When Objective of Work field in Activity in encounter has answer "Any other than above", a field "Specify Other" should be shown.
- [x] In Distribution form, show Village field immediately after the Dispatch Status Id in the same page.
- [x] In Dispatch receipt form, Dispatch Received Date is allowing future date. This should not be allowed.
- [x] In Activity Form, Activity Date should not allow a future date.
- [x] If Activity Sub-type is selected as Others then "Specify Others" field should be displayed.
- [x]  Miscellaneous should only show making/repairing and cleaning, and only numbers (no area etc)
- [x] In Distribution form, Distribution date is allowing future date. This should not be allowed.
- [x] Activity Type is only to be shown if Type of Initiative is DFW. (updated in requirement forms)
- [x] If Activity type is Miscellaneous, then Objective of Work should show the option "Any other not given above"
- [x] Add "Type of Initiative" field in Distribution under Target Community question. Date Type and options updated in requirement sheet.
- [x] Remove "Distribution To" field in Distribution form when Type of Material is Kit. It is not applicable for Kits.
- [x] Change the term "Encounter" to "Form" across application. This will be done through translations.
- [x] Activity Encounter should always be eligible for entry.
- [x] Add "Mohalla / Area" (text type) after the Village field in the Activity form

Translations
- [x] Completed Encounters -> Completed Forms
- [x] Encounter -> Form
- [x] Unplanned Visit -> Filled Form
- [x] Summary -> Received Summary

**Comment by utkarshavni** [comment]
@Gojo-Taqi have added remaining card items also here.

**Comment by AchalaBelokar** [comment]
In Activity Form, Activity Date should not allow a future date.
it is showing me future dates also.
