### ISSUE TITLE
[Goonj] Uploading Locations

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#18]
**Motivation:**
Location hierarchy is currently not uploaded for Goonj. The locations are required to be displayed in forms based on hierarchy.

**Goal:**
Upload location hierarchy in the application. The specific location names should be displayed on forms. 
Demand Registration should show the name of District the user is associated with.
Distribution should show list of Villages to choose from.
Activity should show list of Villages to choose from.

**Acceptance criteria:**
The forms must display correct locations as mentioned above and based on user's catchment.

**Comment by utkarshavni** [comment]
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/goonj/14

Clubbed in a single card

**Comment by Gojo-Taqi** [comment]
Uploaded locations for a few states including Andaman and Nicobar, Chandigardh, Assam, Bihar and Maharashtra.
