### ISSUE TITLE
[Goonj] UAT feedback - Distribution to only show Activities associated with same Village

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#19]
**Motivation:**
Currently all activities done under a specific Demand are shown in the Distribution form to link distribution with Activities. The user should only see activities which are done in the specific village since distribution and activities are village specific.  

**Goal:**
In the Distribution form, under Activities, user should only see Activities which are done in the Village to which Distribution is also associated.
In the Activity form, under related Distribution, user should only see Distributions which are done in the Village to which Activity is also associated.

Logic:

1. Filter for same village as this distribution //TODO
2. Filter out activities already linked to a Distribution //TODO

#1
vActivitiesForSameVillage = encounter.subject.encounters[0] -> e1
filter (e1.encounterType = 'Activity')
filter (e1.Location.uuid == encounter.Location.uuid)

#2.a
acDone = encounter.subject.encounters[0] -> d1
filter (d1.encounterType = 'Distribution')
flatMap (d1.getActivitiesDone());

#2.b
vActivitiesForSameVillage.each -> ve1
filter( ve1 .doesnotExist in acDone)
return filtered values from above.
<END of Logic>

**Acceptance criteria:**
All the activities done in a village should be visible in the Distribution encounter. Activities done in other villages should not be visible. Allow multi-select of activities in a Distribution.
All the distributions done in a village should be visible in the Activity encounter. distributions done in other villages should not be visible. Allow only single-select of Distribution in Activity.

**Comment by Gojo-Taqi** [comment]
Due to platform limitation, it cannot be done for now
