### ISSUE TITLE
[App] Demand Subject Type Creation and Registration

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#2]
Create a Subject Type Demand. 

Type of Subject: Individual.
Location Type:  District
Form: Demand Registration form

The subject details should sync by location as well as Account name it is linked with. So in advanced settings: 
Sync Registration Concept 1 value should be Account Name.

Form Requirement link:
https://docs.google.com/spreadsheets/d/1LXOvcD9DxD5geA79U7ja8icZ-UgmvywS/edit#gid=2090196884

Demand details will be populated through integration with Salesforce - user will not fill the form.

**Comment by AchalaBelokar** [comment]
Account Name should be gray out .. currently  We can not fill the value of Account Name but According to the exel sheet user can fill these value.
