### ISSUE TITLE
Make corrections to Avni Goonj Entity Activity's Fields' options

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#21]
Make corrections to Avni Goonj Entity Activity's Fields' options.
Refer https://docs.google.com/spreadsheets/d/1LC3Nxm7xvbQ0tO0hCjDDpAtxpUWMATDB8ep1fYcTAus/edit#gid=1642600053 for correct and latest mappings.

Incorrect , Older mappings are available at Wrong form belowhttps://docs.google.com/spreadsheets/d/1LXOvcD9DxD5geA79U7ja8icZ-UgmvywS/edit#gid=890770304 for reference / diff.

Measurement type mappings to be done as mapping provided below:
https://docs.google.com/spreadsheets/d/1LC3Nxm7xvbQ0tO0hCjDDpAtxpUWMATDB8ep1fYcTAus/edit#gid=1642600053
Where no values are present, do not show measurement type - as it is working right now.

For which fields to display based on Measurement type, refer to mapping provided below:
https://docs.google.com/spreadsheets/d/1LC3Nxm7xvbQ0tO0hCjDDpAtxpUWMATDB8ep1fYcTAus/edit#gid=2057790581

**Comment by AchalaBelokar** [comment]
1) Activity  Type name should be like this 
   1) Water_Management
   2) Access_Infrastructure
   3)Agriculture_Plantation

**Comment by AchalaBelokar** [comment]
Integration is not working for 
Activity Type: Agriculture Plantation 
Activity  Subtype: Compost pit 
Activity Category: Repairing 

Activity Type: Agriculture Plantation 
Activity  Subtype: Land Bunding
Activity Category: Repairing 
needs to be removed

Activity TypeActivity Type: SanitationActivity
 Sub TypeActivity:  Dustbin 
Activity Category: Repairing
needs to be removed 
Activity TypeActivity Type: Miscellaneous
 Sub TypeActivity:  Truck Unloading 
Activity Category: Cleaning is not working error on there side





Target Community  selected Rohingya Community  it's not working for Demand 88
