### ISSUE TITLE
UAT Deploy for Goonj

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/Goonj#26]
### Acceptance criteria
- Deploy Goonj to UAT

Pending tasks for Vinay for Goonj:

- [x] - Upload Locations
- [x] - Upload catchments
- [x] - Upload users from staging to UAT

**Comment by himeshr** [comment]
Completed following tasks as of now for Power UAT:

- Create org
- Uploaded bundle with locations
- Create Users 

Completed following tasks as of now for Goonj UAT:

- Create org
- Uploaded bundle
- Created few users
- Created LocationTypes
- Configured user groups to contain those users
