### ISSUE TITLE
Handle introduction of new values for TypeOfMaterial field in Dispatch, DispatchReceipt and Distribution

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#28]
Handle introduction of new values for TypeOfMaterial field in Dispatch, DispatchReceipt and Distribution:
Dispatch sync is failing as TypeOfMaterial is other than configured probable values of [Contributed, Kit, Purchase]
"TypeOfMaterial": "Goonj product", "TypeOfMaterial": "Contributed_Track" for few of the DispatchLineItems of "Demand": "2022/ACC-146225/MHR/047". "High Value Material".
- Int mapping to sync Dispatch from Goonj to Avni for all probable values of "TypeOfMaterial" : "High Value Material", "Goonj product", "Contributed_Track"(done)
- Form changes in Dispatch(done), DispatchReceipt (done), Distribution(done)
- Int mapping to handle Distribution sync for entries with TypeOfMaterial  "High Value Material", "Goonj product", "Contributed_Track"(done)

**Comment by AchalaBelokar** [comment]
1 ) Summery is not working for this product
you can refer the 89 demand.

**Comment by himeshr** [comment]
Corrected the Summary rule JavaScript to work in the current state for "TypeOfMaterial" : "High Value Material", "Goonj product", "Contributed_Track" as well.
