### ISSUE TITLE
Find out how app is working with different dispatch status ids across forms. 

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/Goonj#30]
Screen Distribution - Summary & Recommendation - Field ' Dispatch Status id' why is the label (Dispatch) added to it?

**Comment by himeshr** [comment]
We are manually setting the "Dispatch Status Id" using rules written in Distribution form. 
Unfortunately one of the correct ways of doing this was already done in DispatchStatusReceipt, but wasn't replicated for Distribution.
We would now need to make use of same rule and concept as in DispatchStatusReceipt.
Additionally handle fetch of "Dispatch Status Id" from 2 possible fields in integration-server.
