### ISSUE TITLE
Summary rule failure telemetry.

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/Goonj#31]
Stack trace.
getReadableValue@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:118814:19http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:120075:76arrayMap@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:106049:33map@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:110439:20map@[native code]calculateSumOfObservationValuesRecievedgetSubjectSummary@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:236674:37onLoad@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:328725:91http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:325091:42combination@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:408328:38dispatch@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:408040:38dispatchAction@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:144821:48componentWillMount@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:380596:28callComponentWillMount@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:13291:38mountClassInstance@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:13386:33updateClassComponent@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:16131:29performUnitOfWork@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:20296:27workLoop@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:20330:47renderRoot@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:20396:21performWorkOnRoot@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:21134:23performWork@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:21061:30performSyncWork@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:21037:20batchedUpdates$1@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:21222:28batchedUpdates@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:9953:37_receiveRootNodeIDEvent@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:10010:23receiveTouches@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:10040:34__callFunction@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:2579:49http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:2336:31__guard@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:2533:15callFunctionReturnFlushedQueue@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:2335:21callFunctionReturnFlushedQueue@[native code]

error message.
undefined is not an object (near '...}).name;...')

Apparently, the rule fails becoz of the code not written for repeatable question group elements.

**Comment by arjunk** [comment]
someone has to pick this card and log the relevant product bug
