### ISSUE TITLE
Fix the Distribution Form "Material Distributed"."Material" TotalQuantityDistributed * No of Distributions Constraint rule

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#33]
Fix the Distribution Form "Material Distributed"."Material" (TotalQuantityDistributed * No-of-Distributions) Constraint rule.

- [x] The "TotalQuantityDistributed" should allow **zero** for specific material, but should not be zero across sum of all  materials distributed as part of that Distribution encounter.
- [ ] Summary should show exactly which kit/purchased item was distributed. For kits, Kit type and subtype, for others, their name as well as type
- [x] Sort all dashboard cards in the descending order of time

**Comment by Gojo-Taqi** [comment]
Estimated time of completion :- 4 hours

**Comment by sachsk** [comment]
Moving to hold as data is not available
