### ISSUE TITLE
Add two drop down entries in "Activity sub type" in Avni Goonj implementation Activity form in staging and uat.

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#36]
Add two drop down entries in "Activity sub type" in Avni Goonj implementation in staging and uat.

- water management - Pond embankment / ghat and Water storage pit
- Agriculture_plantation - Seed Ball

Fields are highlighted in form : https://docs.google.com/spreadsheets/d/1LC3Nxm7xvbQ0tO0hCjDDpAtxpUWMATDB8ep1fYcTAus/edit#gid=1642600053

**Comment by Gojo-Taqi** [comment]
Estimated time:- 30 min
Time taken :- 45 min
