### ISSUE TITLE
[Goonj] UAT issues

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#37]
- [x] Configure user groups and user assignment in UAT org.
- [x] Fix Search for Account name, not working.
- [x] Primary Dashboard - Two cards displayed for "Activities done - distribution pending". Only one should be displayed.
- [x] Replace the word encounter with "form" via translation at different places in the implementation.
- [x] When Activity Sub type is selected as Canal, Measurement type to be populated should be "Volume" only. (Regression scenario - The units for measurement should populate based on the existing logic of Activity type and Sub type).
- [x] Activity form - Number of days of participation cannot be 0 - Add validation.
- [x] On editing Activity, user is asked to enter district, block and village details again - this should be pre-filled.
- [x] Same issue as above for Distribution, pre-filled values should be shown on edit.
- [x] Moving to next page after selecting geography for distribution, clicking on previous displays no value for geography which were selected earlier. It should show values selected earlier.
- [x] Distribution - Add Kit type and Kit sub Type field in Material distributed section and auto populate those values from Dispatch receipt encounter.
- [x] Distribution - Add Material name field and auto populate it from Dispatch receipt.

We found that, making change specified below adversely affected sync from Avni to Goonj for Distribution and DispatchReceipt, therefore reverted the changes made to hide the elements in the 2 forms.
- [ ] Distribution - Hide Material Id.
- [ ] Distribution - Hide Kit Id.
- [ ] Dispatch Receipt - Hide dispatch line id.

Distribution form:
https://docs.google.com/spreadsheets/d/1LXOvcD9DxD5geA79U7ja8icZ-UgmvywS/edit#gid=1202365536

Dispatch receipt:
https://docs.google.com/spreadsheets/d/1LXOvcD9DxD5geA79U7ja8icZ-UgmvywS/edit#gid=407472636

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-09-19 at 3.47.46 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/0253bdbd-f481-4e00-addd-e04b68dd19f6)
these are the auto-populated values in the dispatch recipient we want to put in distribution.

 Dispatch Receipt - Hide dispatch line id.
