### ISSUE TITLE
[Goonj] Feedback items

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#42]
- [x] Demands not sorted by newest first (these have to be sorted by last modified date time.
- [x] Dispatch status name to be displayed in distribution since Dispatch status id is displayed.
- [x] Kit name to be shown if present (Distribution)
- [x] Register Demand permission to be revoked, it is still there.
- [x] Received Summary does not show Bulk Material or Contributed Track or Goonj Products
- [x] Different items (type of kits) need to be separated out in the summary
- [x] User is able to distribute more items than received. Reefer to below error for reference. Apply this check for Bulk material, Contributed track items and Goonj product as well, it is not there.

Error request body, where distribution done for quantities more than received:
------------------------------------------------------------------------------
{"Distributions":[{"SourceId":"7adcb746-9ea1-4b9c-a181-389e9e208c5d","Block":"Akola","DateOfDistribution":"2022-09-23","DisasterType":null,"DispatchStatus":"a1AHE000000037Z2AQ","District":"Akola","LocalityVillageName":"Agar","NameofAccount":"001HE00000193VyYAI","PhotographInformation":null,"PictureStatus":"Not received","POCId":null,"Remarks":null,"State":"Maharashtra","TypeofCommunity":"Artisans","TypeofInitiative":"Only DFW","DistributionLines":[{"SourceId":"7adcb746-9ea1-4b9c-a181-389e9e208c5d#a19HE0000000BWXYA2","RecordType":"Non Kit Material - Dispatch","DistributedTo":"Families","KitQuantity":0,"MaterialInventory":"a1WHE00000002Mn2AI","Numberofdistributions":20,"Quantity":200,"Unit":"Nos"},{"SourceId":"7adcb746-9ea1-4b9c-a181-389e9e208c5d#a19HE0000000BY9YAM","RecordType":"Non Kit Material - Dispatch","DistributedTo":"Families","KitQuantity":0,"MaterialInventory":"a1WHE00000002LB2AY","Numberofdistributions":10,"Quantity":40,"Unit":"Kg"},{"SourceId":"7adcb746-9ea1-4b9c-a181-389e9e208c5d#a19HE0000000BZlYAM","RecordType":"Kit - Dispatch","Kit":"a1UHE00000003Qv2AI","KitQuantity":80,"Numberofdistributions":0,"Quantity":0},{"SourceId":"7adcb746-9ea1-4b9c-a181-389e9e208c5d#a19HE0000000BbNYAU","RecordType":"Kit - Dispatch","Kit":"a1UHE00000003U92AI","KitQuantity":80,"Numberofdistributions":0,"Quantity":0}],"ActivityIds":[],"CreatedBy":"shivangi@guat","ModifiedBy":"shivangi@guat"}]}

**Comment by utkarshavni** [comment]
@Gojo-Taqi mention comments for unchecked items. (i.e. Not doable, Not reproducable if that is the case)

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-09-26 at 5.56.43 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/9bfbdba1-5586-4edf-a439-2be3b5b6f808)
Received summary is not showing  properly

**Comment by Gojo-Taqi** [comment]
Sorting of demands in newest order is not doable.

**Comment by utkarshavni** [comment]
Moving this to QA failed - last item is still pending. Also, ticking the first item as that has been fixed for dashboard folders which was not working earlier for all of them.

**Comment by AchalaBelokar** [comment]
Dispatch to be received not appearing in sorted order.

![Screenshot 2022-10-11 at 3.59.06 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/07ecfce3-d1e0-4b70-a8f1-c508d01fe602)

**Comment by Gojo-Taqi** [comment]
According to the talk with the client, they want the sorting to be done by last_modified_date_time.
Which is not present in any schema.
We need to get back to the client on this
