### ISSUE TITLE
#[ Goonj] Dispatch receipt is not showing contributed item name.

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/Goonj#44]
Dispatch receipt is not showing contributed item name. It is displaying not known yet.
User : taqi@guat 
Demand Id is 2022/ACC-196157/MHR/034
Salesforce  site : https://goonj--goonjtest.sandbox.lightning.force.com/lightning/page/home
 

![Screenshot 2022-10-11 at 3.26.54 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/0cc1fb28-827b-4968-af97-a4f4434aa6f4)

**Comment by himeshr** [comment]
When  "TypeOfMaterial" is "Contributed", Goonj is sending the name as part of "MaterialName"  field in some cases and in other cases it sends it as part of "ContributedItem".
Example of name as part of "ContributedItem"  field :
                {
                    "Unit": "Gunny Bags",
                    "TypeOfMaterial": "Contributed",
                    "Type": null,
                    "Quantity": 400.00,
                    "PurchaseItemCategory": null,
                    "OtherKitDetails": null,
                    "MaterialName": null,
                    "MaterialId": null,
                    "LastUpdatedDateTime": "2022-10-01T08:56:31.000Z",
                    "KitSubType": null,
                    "KitName": null,
                    "KitId": null,
                    "ItemName": null,
                    "ItemCategory": "Miscellaneous",
                    "DispatchLineItemId": "a19HE0000000GeHYAU",
                    "ContributedItem": "Toys"
                }

Example of name as part of "MaterialName"  field :     
                {
                    "Unit": "Nos",
                    "TypeOfMaterial": "Contributed",
                    "Type": null,
                    "Quantity": 4.00,
                    "PurchaseItemCategory": null,
                    "OtherKitDetails": null,
                    "MaterialName": "ACC-196161-C-Unsorted",
                    "MaterialId": "a1WHE00000002TF2AY",
                    "LastUpdatedDateTime": "2022-10-11T08:52:21.000Z",
                    "KitSubType": null,
                    "KitName": null,
                    "KitId": null,
                    "ItemName": null,
                    "ItemCategory": "Raw Material - Sujni Layer (RM-SJL)",
                    "DispatchLineItemId": "a19HE0000000Jp3YAE",
                    "ContributedItem": null
                }

**Comment by himeshr** [comment]
This would need BA to determine if the correction would be made in Goonj SF to always send the value in only one of the two fields. Or else, implementatio to make changes in form to show the non-empty field's value for ContributedItem.
