### ISSUE TITLE
[Goonj] Dispatch is getting created in Avni on syncing

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#47]
Create a subject for "Dispatch".

Subject Name - Dispatch
Type of subject - Individual

Use case: Dispatch is created in salesforce after receiving demand from the field office. On syncing in Avni, it is created in Avni.

- [x] Clone old Dispatch form
- [x] Void encounter type and create subject type
- [x] Link cloned form to new Subject type
- [x] Correct rules:
    --Demand Summary rule

Form requirements:
https://docs.google.com/spreadsheets/d/1TiccUzEJ6qNRlT2SUC9_FzR_ZD3WU9Xh/edit#gid=1385943251

**Comment by Dinesh2019** [comment]
The dispatch data is not flowing to avin from salesforce.
Test data :
Demand : 2023/ACC-195025/PNB/014
Dispatch : 2023/DEL/ACC-195025/PNB/010
Screenshot from salesforce
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/dd295bcf-8c97-429a-a1cd-a8713f9ada36)
Screenshot from avni 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/6040cc30-40fc-4baa-ae8a-099b812183f2)

**Comment by Dinesh2019** [comment]
We able to see the dispatch data flowing to avin app from salesforce. hence we are moving the ticket to deploy ready
Test Data:
Demand Name : 2023/ACC-195025/PNB/016
Dispatch Name : 2023/DEL/ACC-195025/PNB/013
Screenshot from salesforce:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/0e447bb6-2a1a-4721-8bb9-e82f2a9ff130)
Screenshot of Avni:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/d72b70e2-6a22-45d8-acfc-d32213dac53a)

**Comment by Dinesh2019** [comment]
We able to see the dispatch data flowing to avin app from salesforce. hence we are moving the ticket to deploy ready
Test Data:
Demand Name : 2023/ACC-195025/PNB/016
Dispatch Name : 2023/DEL/ACC-195025/PNB/013
Screenshot from salesforce:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/0e447bb6-2a1a-4721-8bb9-e82f2a9ff130)
Screenshot of Avni:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/d72b70e2-6a22-45d8-acfc-d32213dac53a)
