### ISSUE TITLE
[Goonj] User is able to record an Activity done at distribution site

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#50]
- [x] Clone old Activity form
- [x] Void Activity  encounter type and create subject type Activity 
- [x] Link cloned form to new Subject type Activity 
- [x] Correct rules:
    --Activity Form, FEG Activity Details each FE's rules correction for show answers
    --Handle linking to a Distibution

**Note:** 
EligibilityCheckRule 	===>	Take from EncounterType.encounter_eligibility_check_rule and modify to replace encounters with individual / registration and save in SubjectType.program_eligibility_check_rule									
FE rule	===>	Replace encounter with individual or registration in subjectType.declarative_rule and subjectType.rule

**Comment by AchalaBelokar** [comment]
- [ ] Unable to save activity web app
