### ISSUE TITLE
[Goonj] Showcase feedback  items

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#55]
- [ ] Show subject summary for Dispatch as provided in sheet:
https://docs.google.com/spreadsheets/d/1TiccUzEJ6qNRlT2SUC9_FzR_ZD3WU9Xh/edit#gid=1182557359
- [x] Change "visit date" across forms to "Form modified date" through translation
- [x] Activity form - Activity end date should not allow future date
- [x] Activity form - no of working days should not allow a number greater than the duration covered between activity start date and activity end date days - i.e. If Activity start date is 2nd and end date is 4th, it should not allow user to enter a number greater than 3.
- [x] Activity - enable image capturing fields to capture multiple images
- [x] Search fields for Inventory -  Only keep Kit type and Material in filters.
- [x] Distribution form - Show number of persons only if Activity done has an activity selected.
- [x] Distribution form - Make Activity done non-mandatory
- [x] Distribution form - Move "Distributed to" question to Distribution related details section and show it always.
- [x] Distribution details group form element will be Repeatable question group so that multiple distribution can happen. Refer to sheet - https://docs.google.com/spreadsheets/d/1TiccUzEJ6qNRlT2SUC9_FzR_ZD3WU9Xh/edit#gid=1202365536
- [x] Adding dateTimeStamp query param in implementation inventory.
- [x] Passing two more fields ("TypeOfSchool", "SchoolAanganwadiLearningCenterName") in the distribution request.
- [x] Passing "NoofparticipantsNJPCOther" in the NJPC activity request.

**Comment by arjunk** [comment]
Estimate : 5 hours

**Comment by BEULAHEVANJALIN** [comment]
- Show subject summary for Dispatch as provided in sheet
Does the above point related to dispatch or dispatch receipt? @utkarshavni . Since we don't allow users to register or edit, how can they view the summary?

**Comment by utkarshavni** [comment]
@BEULAHEVANJALIN We should be able to show the summary for subject - Subject summary we can display for any user as long as they have view subject access. By Summary, i mean the summary that will be available on the subject's profile - similar to how we show summary for a program.
