### ISSUE TITLE
Multiple form fields with the same name are displayed in the page on the subjects' details page.

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/Goonj#56]
![duplicatefields.png](https://images.zenhubusercontent.com/6391ce979fce9d1191f3aaac/98ea4cb3-0cb9-4ab5-92e1-b11a53dae33f)

https://staging.avniproject.org/web/subjectProfile?uuid=6202cc76-c5b4-449c-95db-69ab3dcaf9ef
The response of the above api is correct and there is no duplicates.

Seems like the issue is with the following api:
https://staging.avniproject.org/web/form/52c11e75-6e11-4d12-8f42-50f83d130d93

**Comment by himeshr** [comment]
Has been resolved long ago
