### ISSUE TITLE
[App] Distribution form for Distribution encounter.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#6]
Form Name - Distribution

- This will allow the user to enter details of materials they distribute to different communities and the type of material they are distributing.
- Distribution has to be associated with activity as distribution is not done standalone but beneficiaries are engaged in related activities serving some value and purpose. The form should have the option to map Activity (encounter) with the distribution.
- The user should be able to add multiple types of kits/non-kits for materials they are distributing. 

Form Requirements:
https://docs.google.com/spreadsheets/d/1LXOvcD9DxD5geA79U7ja8icZ-UgmvywS/edit#gid=1202365536

**Comment by AchalaBelokar** [comment]
We can not add multiple images

**Comment by AchalaBelokar** [comment]
<img width="416" alt="Screenshot 2022-06-14 at 8 09 12 PM" src="https://user-images.githubusercontent.com/104890488/173605501-c6540e99-6122-400c-8b0a-bd1730258952.png">
distribution quantity is equal to or less than dispatch quantity .

**Comment by AchalaBelokar** [comment]
<
<img width="416" alt="Screenshot 2022-06-14 at 8 14 48 PM" src="https://user-images.githubusercontent.com/104890488/173606829-1c24e701-f04a-43fc-b347-2778dbdc687d.png">
<img width="416" alt="Screenshot 2022-06-14 at 8 16 23 PM" src="https://user-images.githubusercontent.com/104890488/173607191-7021d0a4-6097-431e-9c9b-5460d46ca5a4.png">
 
Distribution quantity is less than or equal to dispatch quantity
