### ISSUE TITLE
[Goonj] Distribution form changes

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#60]
~- [ ] When Inventory is selected in Distribution, its unit should be showed in the form for user to be able to enter quantity correctly.~
~- [x] Current quantity should be displayed and populated in Inventory .~
~- [ ] The number of persons in linking the activity to distribbution cannot be more than number of persons who took part in that activity~

- [x] Auto populate current quantity and original quantity. Original quantity can be on top and followed by current quantity.
- [x] When Material is added its unit should be showed in the form for user to be able to enter quantity correctly.
- [ ] Only the items whose current quantity is not  0  should be shown in the application - user should not be able to save the distribution if selected inventory has quantity as 0.
- [x] Give a check to ensure that quantity specified in distribution should be less than or equal to current quantity of the material selected.
- [x] Activity linking to Distribution. The number of persons in linking the activity to distribution cannot be more than number of persons who took part in that activity. Validation to be added.

**Comment by BEULAHEVANJALIN** [comment]
I tried using a service method **"getSubjectsInLocation"** in rules to access all the subjects in a given address level. But getting an empty array. It would be helpful if the facade service expose other methods as well. Also not sure why getAllNonVoided() method returns empty object. It seems like it even failed in loading the entire db object.


[https://avni.readme.io/docs/writing-rules#using-service-methods-in-the-rules](https://avni.readme.io/docs/writing-rules#using-service-methods-in-the-rules)

Usecase:
I have the individual subject's uuid. Need to get all it's observations in the form rules.

**Comment by BEULAHEVANJALIN** [comment]
Product changes done on 3.39. But needs time till this Thursday (Jun 26) to test and merge to the master branch.

**Comment by utkarshavni** [comment]
Blocked by 
https://github.com/avniproject/avni-client/issues/1033

**Comment by BEULAHEVANJALIN** [comment]
Blocked by 
https://github.com/avniproject/avni-client/commit/5d8fa933725d89fe56481abecee1d2200e7cb63a

**Comment by BEULAHEVANJALIN** [comment]
> For the point she mentioned
> -  Only the items whose current quantity is not 0 should be shown in the application

We don't have such capability to filter out listing based on some condition. 

To be discussed with Arjun and then with shivangi.

Seems like the validations and fields shown on the distribution form are sufficient to move forward with no error. User should have to be aware of not selecting the ones with current quantity 0.

**Comment by Dinesh2019** [comment]
Test Scenario:

- [x] Validate the intial quantity and current quantity is displayed in distribution when the inventory is selected 
- [x] validate the current quantity is less than or erqual to the quantity which we have entered
        sample data current quantity is 45 valiadte the data with 45.1 display the error and 45,less than 45 should not display the any error
- [x] Material units should be displayed in the distrubtion 
- [x]Number of person should be equal or less the number of participation in the activity
      Sample Data : if the number of participation is 5 and the number of person should be equal to less than 5 if it is more than 5 we should displayed with the error
