### ISSUE TITLE
[Goonj] Misc items

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#62]
- [x] Media access issue
- [x] Showing Source Id on Avni app for Activity and Distribution 
Test case 1 - UUID to be displayed while registering Activity/Distribution
Test case 2 - UUID to be displayed on search listing while searching activity within the Distribution form
Test case 3 - UUID to be displayed on Search listing when navigated from home screen and dashboard
- [x] Showing Demand name in Dispatch - Demand name is currently available in GET Dispatch API.
- [x] Source of Material is not displayed on search result fields for Inventory - in the Distribution form.
- [x] Show an option for user to enter Other block name and Other village if Other is selected in the Activity and Distribution Registration.
- [x] Show "Distributed to" as part of the material in Inventory.
- [x] Remove rule to show/hide Number of individuals and No of family members in Specific initiatives Activity based on Distributed to.
- [x] In the subject Search for Activity, add filter for Number of Participants (for S2S activity) and Number of male participants, Number of female participants and Number of other participants for activities which are non-S2S.
- [x] Allow Dispatch received date to be the same as Dispatch registration date in Dispatch receipt form.
- [x] Validation on distribution, when multiple inventories getting created.
- [x] Do not allow same inventory and activity to be linked in the Distribution form.

**Comment by BEULAHEVANJALIN** [comment]
Estimates:
- [x] Media access issue: 2hr
- [x] Showing Demand name in Dispatch: 3-4 hr
- [ ] Source of Material is not displayed on search result fields for Inventory: 1 hr (debugging)
- [x] Show an option for user to enter Other block name and Other village: 3-4 hr (+debugging)
- [x] Show "Distributed to" as part of the material in Inventory: 2 hr
- [x] Allow Dispatch received date to be the same as Dispatch registration date: 1 hr
- [x] Validation on distribution when multiple inventories getting created: 3-4 hr

**Comment by BEULAHEVANJALIN** [comment]
For the point, **Showing Demand name in Dispatch**, I am able to access get dispatch api.

{
    "error": "Unexpected error while processing request : unexpected token: 'AND' \n Class.DispatchService.getDispatches: line 134, column 1",
    "DispatchStatuses": null,
    "DeletedObjects": null
}

**Comment by BEULAHEVANJALIN** [comment]
> - Do not allow same inventory and activity to be linked in the Distribution form.

Added validation only to the inventory as the salesforce accepting two same activities.

```
{
    "Distributions": [
        {
            "sourceId": "58fa4a83-039f-4ddc-983b-730daff4dcf3",
            "state": "Kerala",
            "district": "Alappuzha",
            "block": "tt",
            "localityVillageName": "tt",
            "tolaMohalla": null,
            "dateOfDistribution": "2023-06-28",
            "accountCode": null,
            "nameOfAccount": "Goonj Kochi Test",
            "typeOfCommunity": "Artisans",
            "typeOfInitiative": "CFW-Rahat",
            "photographInformation": "",
            "createdBy": "beulah@gpart",
            "modifiedBy": "beulah@gpart",
            "DistributionLines": [],
            "Activities": [
                {
                    "ActivitySourceId": "dfb260a3-b422-46b6-9b02-23fb23395a16",
                    "numberOfPersons": 1
                },
                {
                    "ActivitySourceId": "dfb260a3-b422-46b6-9b02-23fb23395a16",
                    "numberOfPersons": 2
                }
            ],
            "surveyedBy": null,
            "monitoredByOrDistributor": null,
            "approvedOrVerifiedBy": null,
            "teamOrExternal": null,
            "nameOfPOC": null,
            "pocContactNo": null,
            "reachedTo": null,
            "totalNumberOfReceivers": null,
            "groupName": null,
            "anyOtherDocumentSubmitted": null,
            "reportsCrosschecked": "Yes",
            "name": null,
            "gender": null,
            "age": 0,
            "father_MotherName": null,
            "phoneNumber": null,
            "presentOccupation": null,
            "monthlyIncome": 0,
            "noOfFamilyMember": 0,
            "centreName": null,
            "shareABriefProvidedMaterial": null,
            "howtheMaterialMakesaDifference": null,
            "materialGivenFor": null,
            "noOfIndividualReached": null,
            "remarks": "tt",
            "TypeOfSchool": null,
            "SchoolAanganwadiLearningCenterName": null,
            "disasterType": "Winter",
            "noOfFamiliesReached": null
        }
    ]
}
```

**Comment by BEULAHEVANJALIN** [comment]
Pending things: (All these needs change from the product side.)

- [ ]  Showing Unit and Current quantity for the Material when Inventory is selected in the Distribution form.
- [ ]  Updating Status for Demand and Dispatch
- [ ]  Showing validations when selecting more no of people for activity in distribution
