### ISSUE TITLE
[Goonj] Matching Sync status field for all entities

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#64]
- [x] When the DispatchStatus in GET Demand is "Dispatched" Then the demand should not be shown in the Demands folder.
- [x] Show DemandStatus and DispatchStatus in details of  Demand.
- [x] When the DispatchStage is not null and Not "Reached", then show Dispatch in "Dispatches to be received" folder.
- [x] When the DispatchStage is "Reached" , then show items in "Received Dispatches" folder.
- [x] Show Status and DispatchStage in details of  Dispatch.
- [x] Modify dashboard card to not show the entries for above mentioned Demands and Dispatches

> 

- [x] Other locations issue to be fixed.

**Comment by BEULAHEVANJALIN** [comment]
## Mail from shivangi:

Wish respect to the status fields:-
1. In GET Demand Info 2 status fields have been added:-
DemandStatus and
DispatchStatus

You can show items in the Demand list till the DispatchStatus is not "Dispatched". Once the DispatchStatus is "Dispatched" it should be removed from the list.
Also please show the above 2 status along with Demand information in the details section of Demand.

2. In GET Dispatch, 2 status fields have been added:-
Status &
DispatchStage

Show items in "Dispatches to be Received" list only when DispatchStage is not null and  is not "Reached"

Show items in "Received Dispatches" for which DispatchStage is "Reached" (But this will show Dispatches which were received not using Avni application too, but i guess its okay)

**Comment by BEULAHEVANJALIN** [comment]
Logics for report card:
- Demands to be dispatched:
Demands whose observation for 'Dispatch Status' is not 'Dispatched' AND should not be shown in dispatches' demand ids
- Dispatched to be received:
Dispatches whose observation for 'DispatchStage' is not 'Reached' AND is not null AND dispatches whose encounter haven't happened yet.
- Received Dispatches:
Dispatches whose observation for 'DispatchStage' is 'Reached' OR dispatches with encounter.

**Comment by Dinesh2019** [comment]
- scheduled a call with Arjun to know how to create the dispatch with the In transit status on Friday after standup

**Comment by Dinesh2019** [comment]
Test scenario:

- [x] Tested the demand with demand status: pending,Assigned, Approved,Unattended, and underprocess
- [x] Edit scenario for demand eg: changing status to under process to unattended
- [x] Dispatched stages as Intransit, reached and null
- [x] According to status and stage the dashboard card should be updated.

For some dispatch in the postman, the status is updated as reached but in the client app we are still seeing the status as In-Transit
postman:
![Image 17-07-23 at 4.53 PM.jpeg](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/ca049bb2-3018-4562-ae36-57a7cac8e71b)
Client:
![image_2023_07_17T08_00_36_747Z.jpeg](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/1574c01c-e7a0-46e5-8369-1e040a220228)
