### ISSUE TITLE
[Goonj] Integration Documentation

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#65]
## Points of interest
- Documentation on the systems involved, HL design diagram
- Log monitoring and system visibility
- Additional Credentials for access to integration and freshdesk and other systems
- General support process and Escalation matrix, Point of contact
- Healtchecks frequency
- Healtcheck listeners
- Credentials renewal / expiry
- Implementer guidelines 
- - Steps to introduce metadata changes in UAT org (integration or avni)
- - Testing and green flag
- - Steps to test and migrate to live org (integration or avni)

**Comment by himeshr** [comment]
https://docs.google.com/document/d/1wkvdS5abbgfmQ8uUOoxBaIarBJdxq4UEoZOrr6aghas/edit?usp=sharing
