### ISSUE TITLE
Continue processing Goonj entities flow even if there is an error

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#68]
In-order to have the ability to process from start to end historical data for Goonj, we would need to process all entities without stopping at any failures.
In Goonj Integration.. 
- [x] Continue processing all Goonj entities flow even if there is an error, 
- - Demand
- - DispatchStatus
- - DispatchReceipt
- - InventoryItem
- - Distribution
- - Activity
- [x] Make it a configurable feature in goonj integration 

Tech task:
The new try-catch should throw only if the "catchErrors" property is currently disabled.

**Comment by BEULAHEVANJALIN** [comment]
Duplicate of #69
