### ISSUE TITLE
update the error_type  table based on the error caught while syncing entities

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/Goonj#69]
~- [ ] Create a **ErrorRecordRepository**class and define a method in it called **storeError**.~
~- [ ] **storeError** should perform SQL INSERT operation to store the error information in the **error_type** table when any failure happens during sync.~
~- [ ] Test the record stored for each failure~
~- [ ] Test whether the ErrorRecord works as earlier~

Estimates: 8 hours

In-order to have the ability to process from start to end historical data for Goonj, we would need to process all entities without stopping at any failures.
In Goonj Integration.. 
- [x] Continue processing all Goonj entities flow even if there is an error, 
- - Demand
- - DispatchStatus
- - DispatchReceipt
- - InventoryItem
- - Distribution
- - Activity
- [x] Make it a configurable feature in goonj integration 

## Tech task:
The new try-catch should throw only if the "ignoreErrors" property is currently enabled.

### Requirements: Salesforce system with MH and Kerala Prod Data

- Clear up all previous data in avni organisation created via goonj (we can retain the sql script for it)
~- Clear up all previous data in goonj organisation created via avni.~
- Clear up error records, sync status etc in integration service (we can retain the sql script for it).
- Do a full run.
- After that, the errors that we are seeing needs to be discussed

**Comment by BEULAHEVANJALIN** [comment]
### Testing tasks:

1. Clear up all previous data in avni organisation created via goonj (we can retain the sql script for it)
2. Clear up all previous data in goonj organisation created via avni.
3. Clear up error records, sync status etc in integration service (we can retain the sql script for it).
4. Do a full run. 
5. Post doing the run. Note that the full run means the job executes all the records on both sides.
6. After that, the errors that we are seeing needs to be discussed

**Comment by himeshr** [comment]
We have a final task pending, which is
 - Check the errors that we are seeing and these needs to be discussed
Will work on this after 4.0 release

**Comment by himeshr** [comment]
## Errors encountered so far during Goonj UAT 

#|Error Messages|Count
-|----------|----
1|"400 : ""Answer concept with name=test not found"""|3
2|"400 Bad Request: ""[{""StatusCode"":400,""Records"":null,""error"":""The following error came while we inserting and updating Distribution Activity record - REQUIRED_FIELD_MISSING: Required fields are missing: [Activity__c]; fields that affected this error: (Activity__c)""}]"""|2
3|Answer Mapping entry not found for coded concept answer field: Type|1
4|"400 Bad Request: ""[{""StatusCode"":400,""error"":""The following error has occurred FIELD_CUSTOM_VALIDATION_EXCEPTION: More than one Dispatch Received Status cannot be created for a Dispatch Status.; fields that affected this error: ()"",""DispatchReceivedStatusName"":null,""DispatchReceivedStatusLineItems"":null,""DispatchReceivedStatusId"":null}]"""|1
5|class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')|1
6|"500 : ""Subject type not found with name 'Demand'"""|4705
7|"400 : ""Answer concept with name=DFW not found"""|10
8|""|1
9|"400 : ""Answer concept with name=Adivasis not found"""|7
10|"400 Bad Request: ""[{""StatusCode"":400,""Records"":null,""error"":""The following error has occurred INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST: Type of Community: bad value for restricted picklist field: PWD;fields that affected this error: (Type_of_Community__c)""}]"""|1
11|"400 Bad Request: ""{""Success"":[],""Error"":[{""Record"":""21ae5d16-1e1c-4541-a1f2-b9ed3ca031d1"",""Error"":""Invalid SourceId ""}]}"""|1
12|"502 Bad Gateway: ""<html><CR><LF><head><title>502 Bad Gateway</title></head><CR><LF><body><CR><LF><center><h1>502 Bad Gateway</h1></center><CR><LF></body><CR><LF></html><CR><LF>"""|1
13|"500 : ""Subject type not found with name 'Dispatch'"""|85



## Query used to find the errors:
```
select error_msg, count(*) from error_record_log erl join error_type et on erl.error_type_id = et.id
-- where name in ('UnclassifiedError', 'DistributionAttributesMismatch', 'ImplementationInventoryAttributesMismatch')
where error_msg not like '500 : "Address%' and erl.is_voided = false and et.is_voided = false
group by error_msg;
```

**Comment by himeshr** [comment]
Only errors that need to be looked into are all on the goonj side, rest can be ignored.

Refer attached file for errors to be investigated.
[ErrorsToBeInvestigatedOnGoonj.txt]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckFzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--221c36da99c06c8a9b6d657957fa9dc995073ceb/ErrorsToBeInvestigatedOnGoonj.txt)


#|Action|Owner|Error Messages|Count
-|------|-----|---------|-----|
1 |Ignore|Avni|"400 : ""Answer concept with name=test not found"""|3
2 |INVESTIGATE|Goonj|"400 Bad Request: ""[{""StatusCode"":400,""Records"":null,""error"":""The following error came while we inserting and updating Distribution Activity record - REQUIRED_FIELD_MISSING: R equired fields are missing: [Activity__c]; fields that affected this error: (Activity__c)""}]"""|2
3 |Ignore|Avni|Answer Mapping entry not found for coded concept answer field: Type|1
4 |Ignore|Avni|"400 Bad Request: ""[{""StatusCode"":400,""error"":""The following error has occurred FIELD_CUSTOM_VALIDATION_EXCEPTION: More than one Dispatch Received Status cannot be created for a  Dispatch Status.; fields that affected this error: ()"",""DispatchReceivedStatusName"":null,""DispatchReceivedStatusLineItems"":null,""DispatchReceivedStatusId"":null}]"""|1
5 |Ignore|Avni|class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')|1
6 |Ignore|Avni|"500 : ""Subject type not found with name 'Demand'"""|4705
7 |Ignore|Avni|"400 : ""Answer concept with name=DFW not found"""|10
8 |Ignore|Avni|"400 : ""Answer concept with name=Adivasis not found"""|7
9|Ignore|Avni|"500 : ""Subject type not found with name 'Dispatch'"""|85
10|INVESTIGATE|Goonj|"400 Bad Request: ""[{""StatusCode"":400,""Records"":null,""error"":""The following error has occurred INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST: Type of Community: bad value for restricted picklist field: PWD;fields that affected this error: (Type_of_Community__c)""}]"""|1
11|Ignore|Avni|"400 Bad Request: ""{""Success"":[],""Error"":[{""Record"":""21ae5d16-1e1c-4541-a1f2-b9ed3ca031d1"",""Error"":""Invalid SourceId ""}]}"""|1
12|Ignore|Avni|"502 Bad Gateway: ""<html><CR><LF><head><title>502 Bad Gateway</title></head><CR><LF><body><CR><LF><center><h1>502 Bad Gateway</h1></center><CR><LF></body><CR><LF></html><CR><LF>"""|1
