### ISSUE TITLE
[App] Activity form for Activity encounter

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#7]
Form name - Activity

This will have details for all the activities carried out by field users before or after the dispatch - community members are engaged in any activity for distribution - the distribution is not done for the sake of it and has a rationale associated with it which is served through activities.

Form Requirements:
https://docs.google.com/spreadsheets/d/1LXOvcD9DxD5geA79U7ja8icZ-UgmvywS/edit#gid=890770304

**Comment by AchalaBelokar** [comment]
1) Number of days of Participation should be less than or equal to  total no of Activity start date and Activity end date.
2) Sanitation spelling is wrong.
