### ISSUE TITLE
Validation parity between Salesforce and Avni

### ISSUE THREAD

**Issue by arjunk** [avniproject/Goonj#70]
This sheet has validations from Salesforce
https://docs.google.com/spreadsheets/d/1LC3Nxm7xvbQ0tO0hCjDDpAtxpUWMATDB8ep1fYcTAus/edit#gid=1486024760

**Comment by BEULAHEVANJALIN** [comment]
Missing validations:
- [x] noOfParticipantsS2S cannot be 0
- [ ] sum(noOfparticipantsFemaleCFW , noOfparticipantsMaleCFW, NoofparticipantsCFWOther) cannot be 0
- [ ] noOfParticipantsFemaleNJPC cannot be 0
- [ ] noOfDaysOfParticipationS2S, noOfDaysOfParticipationNJPC cannot be 0 (including the validation which is already there)

**Comment by BEULAHEVANJALIN** [comment]
Moving this to prod dependency as this is depends on the following bug
https://github.com/avniproject/avni-client/issues/1069
