### ISSUE TITLE
UAT feedback items (as on Aug 08)

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/Goonj#72]
- [x] Break all the questions from the 'Number of Participants' question group.
- [x] Make necessary changes in the integration code as well.
- [x] Write script to update existing observations.
- [x] Display all concepts related to the number of people in the activity's search result field.

- Add the following validations:

- [x] noOfParticipantsS2S cannot be 0
- [x] sum(noOfparticipantsFemaleCFW , noOfparticipantsMaleCFW, NoofparticipantsCFWOther) cannot be 0
- [x] noOfParticipantsFemaleNJPC cannot be 0
- [x] noOfDaysOfParticipationS2S, noOfDaysOfParticipationNJPC cannot be 0 (including the validation which is already there) 
- [x] Either NoOfIndividualReached or NoOfFamiliesReached must be filled, neither of which can be 0.

Reference
https://docs.google.com/spreadsheets/d/14lq2h97IRWXdnPjRczqTCmzxxFCw-hw1ShjyLoPk_TY/edit#gid=2059414540

**Comment by Dinesh2019** [comment]
Test Scenario:

1. Number of people displayed in the activity search
2.No of participants s2s with values as 0 and negative value
3. sum(noOfparticipantsFemaleCFW , noOfparticipantsMaleCFW, NoofparticipantsCFWOther)  values as 0 and negative value
4. noOfParticipantsFemaleNJPC cannot be o validated the value as 0 and negative value
5. Either NoOfIndividualReached or NoOfFamiliesReached must be filled, neither of which can be 0.

**Comment by BEULAHEVANJALIN** [comment]
https://gist.github.com/BEULAHEVANJALIN/746b58a5bd3e59a9e58d0b156ba7ef1d
