### ISSUE TITLE
Setup Approval Workflow

### ISSUE THREAD

**Issue by arjunk** [avniproject/Goonj#75]
1. Approval Workflow should be setup for following entities
2. There should be two users groups 
3. Approval status should sync to Salesforce as "Reports cross checked"

**Comment by himeshr** [comment]
@arjunk is this required to be done.?

**Comment by himeshr** [comment]
Closing this, as this would not be viable for Goonj Go Live at this point.
Excerpts from Arjun's Mail to Shivangi:
```
Setting up the approval flow in the app is simple. However, we just had an internal discussion and the following is missing and will require analysis and not-so-insignificant effort. 

1. Approval status in external API
2. Handling this in integration service

So we should plan to go live without this and discuss this part of phase 2.  

```
