### ISSUE TITLE
Re upload images, to recover from missing images error from Phase 1

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#78]
## Re upload images, to recover from missing images error from Phase 1

This is a follow up action corresponding to the bug fixed as part of avniproject/avni-client#1156 in release 5.1.0 (Apk v5.1.0)
Action to be done after Nov 16th 2023, in-coordination with Shivangi.

 - Goonj field users should upgrade their avni-client APKs to latest release version (v5.1.0)
 - Modify "Field users" UserGroup privileges to allow Edit of "Activity" subjectType 
 - After field users complete re-upload activity and admins confirm success of correction, 
     - Modify the "Field users" UserGroup privileges to disallow Edit of "Activity" subjectType

**Comment by himeshr** [comment]
Upload in progress from Goonj Users.

After they are done, remove all users for Goonj "Edit forms temp group" user group., and close this card.

**Comment by vaijayanthisundaram** [comment]
@himeshr Please update the status on this as the implementation team is not aware of status.

**Comment by nupoorkhandelwal** [comment]
Closing this card, as per Himesh the action item is on Shivangi.
