### ISSUE TITLE
Show Tola/Mohalla in Distribution and Activity list

### ISSUE THREAD

**Issue by sachsk** [avniproject/Goonj#82]
FD: https://avni.freshdesk.com/a/tickets/3340

## Context 

Add the "Tola / Mohalla" in the search result field and test it.

Note: test this on Goonj Demo first.

**Comment by Dinesh2019** [comment]
Test execution video :

https://drive.google.com/drive/folders/15Do0hEO24Cxe7V2fK8lNGeLAVnqpAS8t

**Comment by vedfordev** [comment]
@Dinesh2019 moved changes to prod
