### ISSUE TITLE
[Goonj Support] Some rule change in Distribution Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Goonj#83]
## Support ticket 
 https://avni.freshdesk.com/a/tickets/3338

## Change and context 

@Avni Support team, 
    After discussion with Vinay, Vivek and Maha, we have come to the conclusion that, we Support team would need to make use of IndividualServiceFacade.getSubjectByUUID(currentdistributionUUID) to compute the difference in ImplementationInventory Items Quantity in old and new Distribution. Based on the difference value, they have to determine whether the value Exceeds available Inventory quantity and if yes, then an Error has to be thrown.

## Tech details
 In Goonj org, Distribution form. For "Inventory details" FEG, "Quantity" FormElement, the rule should be enhanced as follows:
Current check: quantity > currentQuantity
New Check: (newDistributionQuantity - oldDistributionQuantity) > currentInventoryQuantity

Where,
 - newDistributionQuantity and quantity, refer to current value entered in form for the distribution.
 - currentQuantity and currentInventoryQuantity refer to inventory value fetched using individualService.
 - Use individualService, to fetch oldDistributionQuantity from Distribution stored in DB.

**Comment by BEULAHEVANJALIN** [comment]
### Tech tasks:
- Get the Inventory ID from the Current Distribution: (REFER FOLLOWING SCRIPT)
```
individual.findGroupedObservation(observationUUID)[params.questionGroupIndex].findObservationByConceptUUID(inventoryIdUUID).getReadableValue();

```
- Fetch all distributions in the same location:
```
individualService.getSubjectsInLocation(individual.lowestAddressLevel, 'Distribution')
  ```
- Filter Distributions to Identify Those Matching Our Inventory ID:
```
// Example function to check if any observation in a distribution matches the given inventoryId (THIS IS JUST EXAMPLE, WHOEVER PICKS PLEASE REWRITE AS REQUIRED)
function someObservationMatches(distribution, inventoryId) {
    return distribution.observations.some(observation => 
        observation.inventoryId === inventoryId);
}

const relevantDistributions = distributions.filter(distribution => 
    someObservationMatches(distribution, inventoryId) && distribution.uuid !== individual.uuid);
```
- From the filtered distributions, find the one with the latest registration date that is earlier than the registration date of the current individual.
```
```
- Once the relevant distribution is identified, proceed to retrieve the required data from it. i.e., `oldDistributionQuantity`
 

##### mentioned to use the registration date since it never changes, making it easier to fetch the previous distribution.

**Comment by vedfordev** [comment]
@nupoorkhandelwal 

assign ticket to product support group. moving back to support ready. 

new rule backup :

```
'use strict';
({params, imports}) => {
    const individual = params.entity;
    const moment = imports.moment;
    const formElement = params.formElement;
    const individualService = params.services.individualService;
    const _ = imports.lodash;
    let visibility = true;
    let value = null;
    let answersToSkip = [];
    let validationErrors = [];

    // console.log('individual:', individual);
    // console.log('individualService:', individualService);
    // console.log('params:', params);

    const condition11 = new imports.rulesConfig.RuleCondition({
        individual,
        formElement
    }).when.questionGroupValueInRegistration("ccf1fbd6-d59c-40d3-a05a-f31cd6ac2cad", "bafb80ac-6088-4649-8ed3-0501e1296c6e", params.questionGroupIndex).defined.matches();

    if (condition11) {
        let currentRepeatableGroupObservation = individual.findGroupedObservation('bafb80ac-6088-4649-8ed3-0501e1296c6e')[params.questionGroupIndex];
        let inventoryUUID;
        let currentInventoryQuantity;
        let newDistributionQuantity;
        let oldDistributionQuantity;
        let currentInventoryQuantityUUID = '080aca7e-c590-4036-bee7-cf3f77b488aa';

        if (currentRepeatableGroupObservation != undefined) {
            inventoryUUID = currentRepeatableGroupObservation.findObservationByConceptUUID('ccf1fbd6-d59c-40d3-a05a-f31cd6ac2cad').getReadableValue();
            let quantityobs = currentRepeatableGroupObservation.findObservationByConceptUUID('bf591bee-f3a5-4481-9b01-ab40ca01c8b4');
            if (quantityobs != undefined) {
              newDistributionQuantity = quantityobs.getReadableValue();
            }
        }
        
        
        
        if (inventoryUUID != undefined) {
            currentInventoryQuantity = individualService.getSubjectByUUID(inventoryUUID).getObservationReadableValue(currentInventoryQuantityUUID);         
        }
        
        
        let currentdistributionUUID = individual.uuid;
        let oldDistribution = individualService.getSubjectByUUID(currentdistributionUUID);
        let rpg = oldDistribution.findGroupedObservation('bafb80ac-6088-4649-8ed3-0501e1296c6e')[params.questionGroupIndex];

        
        if(rpg != undefined){
          let qutobs = rpg.findObservationByConceptUUID('bf591bee-f3a5-4481-9b01-ab40ca01c8b4');
          
          if(qutobs != undefined){
            oldDistributionQuantity = qutobs.getReadableValue();
          }
          
        }
       
        
        console.log(`currentInventoryQuantity ${currentInventoryQuantity} newDistributionQuantity ${newDistributionQuantity} oldDistributionQuantity ${oldDistributionQuantity} quantity ${currentInventoryQuantity}`);     


        if (currentInventoryQuantity != undefined && newDistributionQuantity != undefined && oldDistributionQuantity != undefined && (newDistributionQuantity - oldDistributionQuantity)>currentInventoryQuantity) {
            validationErrors.push("Quantity shouldn't be greater than the current quantity");
        }
    }
    return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility, value, answersToSkip, validationErrors);
};
```

**Comment by Dinesh2019** [comment]
@vinayvenu @himeshr we have the logic written as  (newDistributionQuantity - oldDistributionQuantity) > currentInventoryQuantity but as a user I don't have the value displayed what is the old distribution quantity in order to validate.

**Comment by himeshr** [comment]
> @vinayvenu @himeshr we have the logic written as (newDistributionQuantity - oldDistributionQuantity) > currentInventoryQuantity but as a user I don't have the value displayed what is the old distribution quantity in order to validate.

The old distribution quantity is the one which was set for the "Quantity" field before User clicked on Edit button of the Distribution. Its value changes with multiple edits of the same Distribution, ending up with not being in sync with Inventory values in Salesforce and / or the Client. And hence edits should be done sparsely for the Distributions Quantity.
