### ISSUE TITLE
[Goonj Support] Create a metabase report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Goonj#84]
## Support ticket 
https://avni.freshdesk.com/a/tickets/3377

## Tech tasks

- [x] 1. Use avni_int database connection available on metabase 
- [x] 2. Using following query, create a report 
```
select er.id, et.name, et.follow_up_step, er.avni_entity_type, er.integrating_entity_type, er.entity_id, erl.logged_at, erl.error_msg
from error_record er join error_record_log erl on er.id = erl.error_record_id
join error_type et on erl.error_type_id = et.id
where er.integration_system_id = 2;
```
- [x] 3.Add date filter on logged_at
- [x] 4. Add field filters on the all the possible columns displayed in the reports
- [ ] 5. Once QA is done create login for following users - 
shivangi@goonj.org
data@goonj.org

**Comment by himeshr** [comment]
After review, suggested adding this select value, to make the results more readable..

```
CASE
  WHEN (error_type.follow_up_step = '0') THEN 'Process(0)'
  WHEN (error_type.follow_up_step = '1') THEN 'Terminal(1)'
  WHEN (error_type.follow_up_step = '2') THEN 'Internal(2)'
  WHEN (error_type.follow_up_step = '3') THEN 'External(3)'
 END AS  "Followup step"
```

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal you can proceed with creating the users
