### ISSUE TITLE
[Goonj Support] Upload locations to prod org

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Goonj#85]
## Support ticket 
https://avni.freshdesk.com/a/tickets/3413

## Tech tasks 

- [x] Get the locations dump for Karnataka state for the following districts:-
Belagavi, Davanager, Chitradurga, Vijayanagara, Koppal, Raichur
using the script below -  https://drive.google.com/drive/folders/1eYbo_mOy5RFSkIr4FGhPvY8rqsvbORvB

- [x] Upload this locations csv to the prod organisation
- [x] Create catchments for each of the above districts

**Comment by vedfordev** [comment]
@nupoorkhandelwal  Davanager and Vijayanagara was not present in db dump. please check with client.

**Comment by vedfordev** [comment]
@nupoorkhandelwal we upload 'Davangere','Vijayanagar'.
