### ISSUE TITLE
[Goonj Support] Improve offline dashboard cards performance

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Goonj#86]
## Support ticket
https://avni.freshdesk.com/a/tickets/3495

## Following below things would help to write more optimised queries:
1. Referring this readme link
2. Trying out the realm queries in realmdb
3. Understanding where to optimise/how long each card takes from prod-dev apk.

**Comment by Gojo-Taqi** [comment]
I have updated the rules of all 9 report cards, and I am attaching the times before and after using realm queries.

Demands to be dispatched			Before - 37,55	 	After - 5,9
Dispatches to be received			Before - 19,16		After - 2,3
Received dispatches				Before - 53,57		After - 7,6
Activities done					Before - 19,23		After - 2,2
Distributions done				Before - 4,5		After - 2,2
Total Inventories				Before - 5,3		After - 1,2
Activities linked to distribution		Before - 100, 91	After - 14,19
Activites not linked to distribution		Before - 106,128	After - 14,18
Distributions without activities		Before - 19,14		After - 12,13

**Comment by Gojo-Taqi** [comment]
Since vedant uploaded the uat bundle to production today, marking the card as closed.
