### ISSUE TITLE
Rule failure for goonj uat and production

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/Goonj#87]
Rule uuid - 'd2a3d328-0775-4cdd-a0b1-f0f6c395341f'

- [x] Debug and fix the rule both in uat
- [x] Close all the rules with that rule uuid once it is fixed
- [x] Move the changes to prod after QA and close all the logs with that rule uuid.

**Comment by BEULAHEVANJALIN** [comment]
Added the following check. oldDistribution was undefined earlier
```
let oldDistribution = individualService.getSubjectByUUID(currentdistributionUUID);
if (oldDistribution !== undefined) {
  // oldDistribution was undefined earlier
}
```

---
```sql
set role gvamp_uat;

select *
from rule_failure_telemetry
where rule_uuid = 'd2a3d328-0775-4cdd-a0b1-f0f6c395341f'
  and is_closed is false
order by last_modified_date_time desc;

update rule_failure_telemetry
set is_closed        = true,
    closed_date_time = current_timestamp
where rule_uuid = 'd2a3d328-0775-4cdd-a0b1-f0f6c395341f'
  and is_closed is false
  and organisation_id = 356;
```
Closed 235 rule failures in gvamp_uat as part of this card. The same need to be done in prod. Fresh dev is in progress.
@vedfordev, please inform me once you've uploaded the UAT bundle of Goonj to prod.
