### ISSUE TITLE
Goonj phase 2 implementation changes

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/Goonj#88]
- [x] Total inventories report card should count only items whose current quantity is greater than 0
- [x] Add filters on the offline dashboard to filter based on location and account. Modify all report cards to respect this field
- [x] Make changes to activity type, subtype and measurements based on https://docs.google.com/spreadsheets/d/1Hz6frFs1Nj9YPE2ia1E2XlWSIIn_2iVG6GYbnO2tUgE/edit?usp=sharing

#### Distributions form

- [x] Disclaimer Photographs (Photograph Field for adding Disclaimer Photographs-multiple) -optional (field to be added in salesforce and API) - Before Distribution Related Details/Image
- [x] Receiver List Photographs (Photograph Field for adding Disclaimer Photographs-multiple) -optional (field to be added in salesforce and API) - After Distribution Related Details/Image
- [x] Total Number of Receivers:- Number field - mandatory (field to be added in salesforce and API) - After Inventory Details Question Group in the same page
- [x] Target Community - Should be Multiselect (API will be affected)
- [x] Number of Distributions (within Inventory Details) - To be removed from Avni
- [x] Move Inventory Details and Activities done to just before "Other Details" section
- [x] If the "Dispatch Received Date" associated with implementation inventory is greater than the "Distribution date" then show error "Inventory received date is after distribution date"

#### Dispatch Receipt

- [x] Add "Other Details" section at the end with one question - Remarks (Mandatory, text)

#### Activity

- [x] Add "Was Disclaimer Form Filled?" Yes/No - Default No, mandatory as last question in Activity Details
- [x] Add "Other Details" section at the end with question "Form Cross Checked?" Yes/No - Default No, mandatory
- [x] Add field Remarks:- text field (optional) after "Form Cross Checked" field
- [x] Objective in Activity should be multi select

**Comment by vedfordev** [comment]
will work after client response.

**Comment by vedfordev** [comment]
@vinayvenu move card to freshdev ready as some requirement are on client end. 
As I discussed with @himeshr default child level of location selection is done for rwb gramin. Avni it will come in. next release.

**Comment by Dinesh2019** [comment]
- [x] Nursey Making - to be newly added in Salesforce and Avni need to be area

**Comment by mahalakshme** [comment]
@vinayvenu no rules uses, target community and objective of work?
