### ISSUE TITLE
UAT feedback for 2024 changes

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/Goonj#91]
Feedback sheet here - https://docs.google.com/spreadsheets/d/1w_nA2ke0a0vtgCvQ5sDZPp7y4O8mMDsLbOj8WmAaYBg/edit?usp=sharing

### In scope
Issues 2, 3 and 10

**Comment by vedfordev** [comment]
For 10th point raise product bug card [Link](https://github.com/avniproject/avni-client/issues/1373)
For filter raised product bug card [Link](https://github.com/avniproject/avni-client/issues/1375) [Link](https://github.com/avniproject/avni-client/issues/1393)

**Comment by vinayvenu** [comment]
@Dinesh2019 can you confirm if item 3 on the spreadsheet is good?

**Comment by Dinesh2019** [comment]
@vinayvenu yeah vinay looks good

**Comment by vedfordev** [comment]
@vinayvenu @Dinesh2019 move card to on hold because we still have dashboard filter issue  [Link](https://github.com/avniproject/avni-client/issues/1393)

**Comment by vedfordev** [comment]
@vinayvenu @Dinesh2019 as we deployed to prod I am closing this card.
