### ISSUE TITLE
2024 changes - Integration Service changes

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/Goonj#92]
Apply changes mentioned in https://github.com/avniproject/integration-service/issues/121

**Comment by vedfordev** [comment]
@vinayvenu moved card to in code review.

**Comment by Dinesh2019** [comment]
- [ ] App is getting break 
version : 7.2.1
old version : 7.0.1

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVY4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed700ccc98767f7bea7ba33c2f4fc55cb32313d4/Screen%20Recording%202024-04-22%20at%206.55.21%E2%80%AFAM.mov

**Comment by vinayvenu** [comment]
@Dinesh2019 this is because the inventory item is not found in the local database. You will need to ensure that all users have the same account names across all subject types.

**Comment by Dinesh2019** [comment]
I think integration is not happening.

Created the Activity in the app and validated the in the Salesforce 

<img width="372" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3FLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cc7cae531fd2600ddaee1e37ae38017c2672683/Screenshot%202024-04-23%20at%205.20.44%E2%80%AFPM.png" alt="Screenshot 2024-04-23 at 5.20.44 PM.png" />

did the vice versa scenario :

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3VLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8c83fea8c67610816d9a6c52eee541f75693786/Screenshot%202024-04-24%20at%209.15.06%E2%80%AFAM.png" alt="Screenshot 2024-04-24 at 9.15.06 AM.png" />

Client app :


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3lLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72520d847a5b3a4c03a17261d16fbd24d2985fcb/Screen%20Recording%202024-04-24%20at%209.16.36%E2%80%AFAM.mov
