### ISSUE TITLE
Add validation error for the file "Total Number of Families Reached" in Distribution registration form

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/Goonj#94]
Currently, this field allows the users to enter values in terms of decimals(double, float, etc..).

- [x] Add a validation error such that whenever a decimal point/value is added, it gives the user an error.
- [x] Regex expressions can be used to achieve the above.

**Comment by BEULAHEVANJALIN** [comment]
@Dinesh2019 Please test this once again before closing.

**Comment by Dinesh2019** [comment]
@BEULAHEVANJALIN tested in prod also only for QA references.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2p6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ce332ee6047bc0a83329f59e123109a59275987/Screenshot%202024-05-20%20at%2010.59.11%E2%80%AFAM.png" alt="Screenshot 2024-05-20 at 10.59.11 AM.png" />
