### ISSUE TITLE
Goonj UAT Feedback 1 May

### ISSUE THREAD

**Issue by vedfordev** [avniproject/Goonj#96]
Feedback Sheet : [Link](https://docs.google.com/spreadsheets/d/1BsY9V1-mEg06_lxAF8C_WwbFD3K457poU1DmKDzhcEY/edit#gid=0)

Work on Point 4,8,10

**Comment by Dinesh2019** [comment]
Added comments is the sheet and asked reply from shivaangi if we face the issue we are reopen the ticket
