### ISSUE TITLE
UAT feedback sweep 2

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/Goonj#97]
UAT sheet - https://docs.google.com/spreadsheets/d/1BsY9V1-mEg06_lxAF8C_WwbFD3K457poU1DmKDzhcEY/edit?usp=sharing

Items to be fixed - Everything from line number 10 to 16

PS: @Dinesh2019 please mark status on the sheet once testing is over

**Comment by vedfordev** [comment]
@vinayvenu / @Dinesh2019  as we discussed only point 14 require changes.
